- validator/validation/graphics.py
One thing i noticed: Both functions (generate_overview_map and generate_boxplot) start with an if-statement (if not validation_run.output_file: return None). I think this code should move into the generate_all_graphs function, otherwise line 116 might throw an error. Another solution might be to add this code to line 204 in validator/validation/validation.py, but i don't want to touch code outside graphics.py. Apart from that everything should work fine.
The seaborn library is used for creating the boxplot and needs to be installed (conda install seaborn).
> updated plotting functions

- docs/developers_guide.md
- environment/create_conda_env.sh
- requirements.txt
- validator/fixtures/datasets.json
- validator/fixtures/variables.json
- validator/fixtures/versions.json
- validator/static/files/ISMN_v20190222_Readme.txt
- validator/templates/validator/datasets.html
- validator/validation/globals.py
- validator/validation/graphics.py
- validator/validation/readers.py
Adding esa cci sm combined dataset to qa4sm.
> Add cci dataset

- docs/developers_guide.md
- environment/create_conda_env.sh
- requirements.txt
- validator/fixtures/datasets.json
- validator/fixtures/filters.json
- validator/fixtures/variables.json
- validator/fixtures/versions.json
- validator/validation/filters.py
- validator/validation/globals.py
- validator/validation/graphics.py
- validator/validation/readers.py
This change will add the SMOS data.
Please merge this pull request after "Add cci dataset #4" has been merged.
I merged that one into my changes here with the intention to make the merge of this pull request easier. Hope it works out.
> Smos reader1

- validator/tests/test_validation.py
- validator/validation/graphics.py
This pull request should fix the problem for the global ERA dataset. Also it includes a test case for the ERA dataset for the long test run
> fix bug for  ERA dataset graph generation and add automatic test for ERA

- docs/developers_guide.md
Minor changes to installation guide after going through this to install at TU Wien
> updated installation guide

- environment/create_conda_env.sh
- init_config.sh
- settings_example_conf.py
- valentina/settings.py
Fix environment creation and settings
> Fix environment creation and settings

- validator/static/css/scheme.css
- validator/static/js/results_buttons.js
- validator/templates/validator/publishing_dialog.html
- validator/templates/validator/result.html
- validator/templates/validator/user_runs.html
- validator/tests/test_views.py
- validator/views/results.py
* edit and save button added, edit_name and monika function created
* ids changed into classes, now function works on each validations separately :)
* buttons added to the result view, some improvements of functions added
* all needed improvements added, and changing names works
* saving a new name added to the result view
* save_name function changed name to ajax_save_name, cancel_saving function added, cancel button added to user_runs.html
* space around validation name removed in user_runs.html and title of saving button changed in result.html
* some cleansing in html files
* styles of edit, save and cancel buttons added to scheme.css
* functions connected to edit, save and cancel button finished and saved in result_buttons.js file
* code duplication removed
* some data printing …
> Qa4sm 157 (#30)

- environment/qa4sm_env.yml
- validator/templates/validator/result.html
- validator/tests/test_validation.py
- validator/validation/globals.py
- validator/validation/graphics.py
- validator/validation/validation.py
- validator/views/results.py
* Make publishing test optional
* Add plots from qa4sm-reader, make reference ds id always 0
* Update conda creation script with packages for plotting
* Fix dataset pairs for GUI, add dependencies
* Update ismn version
* Remove test skipping and install pytesmo from github for now
* Dont skip tests for n ow
* Make 2 tests that need DOI token optional
* Add os
* Set model attr that indicates new dataset order
* Update model
* Derive pair names from plot files directly
* Update map description
* Center mapplot
* Add TCol and plots
* Add tc test
> Tcol (#52)

- environment/create_conda_env.sh
- environment/qa4sm_env.yml
- use pytest==5.4.3 for now, otherwise `maintenance_mode_switching` fails
> Update environment file with pinned pytest

- validator/fixtures/filters.json
- validator/static/css/scheme.css
- validator/templates/widgets/filter_checkbox_option.html
- checkbox for param filters checked and disabled;
- new style introduced for param filters checkbox;
- new help text added;
> Checkbox param filters

- validator/fixtures/versions.json
- validator/static/css/scheme.css
- validator/templates/widgets/filter_checkbox_option.html
Some small bug corrections applied
> Bug fixing

- validator/templates/validator/validate.html
Minimum and maximum date added, range of year set to our range.
> Improve calendar

- validator/templates/validator/published_results.html
- validator/templates/validator/user_runs.html
Add text to empty validations page and hide sorting form
> adds text to empty validation page

- validator/management/commands/setdatasetpaths.py
making possible to call manage.py setdatasetpaths with a path parameter so that it can be called from the deployment script
> add parameter to set dataset path command

- .github/workflows/test.yml
Added long running tests and graph tests
> Update GitHub build

- validator/fixtures/filters.json
- validator/fixtures/networks.json
- validator/fixtures/variables.json
- validator/tests/test_hacks.py
- validator/tests/test_validation.py
- validator/validation/batches.py
- validator/validation/filters.py
- validator/validation/globals.py
- validator/validation/validation.py
Reverts awst-austria/qa4sm#176
> Revert "Review new ismn package"

- UI/src/app/modules/core/services/validation-run/validationrun.service.ts
- UI/src/app/modules/validation-result/components/buttons/buttons.component.html
- UI/src/app/modules/validation-result/components/buttons/buttons.component.scss
- UI/src/app/modules/validation-result/components/validationrun-row/validationrun-row.component.html
I improved conditions for headers icons and changed styling for edit name button
> New UI fix conditions on validationrun pages

- UI/src/app/modules/validation-result/components/buttons/buttons.component.html
- UI/src/app/modules/validation-result/components/buttons/buttons.component.ts
- validator/models/validation_run.py
some changes to downloaded file names applied
> New UI graphs name update

- UI/package-lock.json
- UI/package.json
- UI/src/app/modules/dataset/components/dataset/dataset.component.html
- UI/src/app/modules/dataset/components/dataset/dataset.component.ts
- UI/src/app/pages/validate/validate.component.ts
function for setting default time range added
> New UI set default time range

- validator/forms/data_configuration.py
- validator/templates/validator/validate.html
- validator/tests/test_views.py
- getting valrun.initial_tcol as bool instead of string
- initial version set correctly
- some tests
> bugfixes related to loading settings

- environment/qa4sm_env.yml
- validator/validation/validation.py
> use new temporal matcher and metric calculators

- environment/qa4sm_env.yml
updated environment of reader to latest release
> update environment file

- docs/release_procedure.md
- environment/qa4sm_env.yml
environment update before deployment
> env updated, release procedure updated

- environment/qa4sm_env.yml
New reader version (4.4.3), that fixes issue with negative values in statistics table
> updated reader path

- validator/validation/batches.py
- validator/validation/globals.py
Added the fields:
- `instrument_depthfrom`
- `instrument_depthto`
to the metadata dictionary, providing depth information for the metadata plots
> Depth information in metadata

- environment/qa4sm_env.yml
- validator/templates/validator/validate.html
- validator/validation/readers.py
1. Environment updated;
2. Clear coordinates button disabled when HR data chosen;
3. Coordinates limits applied when choosing spatial subsetting on the map;
> Fix limiting spatial subsettings

- api/tests/test_comparison.py
- api/views/comparison_view.py
- api/views/validation_run_view.py
> API Comparison Tests

- UI/src/app/pages/validate/validate.component.ts
- validator/validation/globals.py
Added hires datasets to reference
> Added hires to references

- environment/qa4sm_env.yml
- validator/fixtures/datasets.json
- validator/fixtures/versions.json
- validator/tests/auxiliary_functions.py
- validator/validation/globals.py
Changed fixture names and updated reader environment
> Smos l3 names

- validator/mailer.py
- validator/models/email.py
* function changed to send emails separately to each user on the list
* sending emails updated
> Fix mailer (#453)

- validator/fixtures/networks.json
Added the new ismn versions to resp. networks. Maybe we can fill this file somehow automatically from the data on the server? It's very error-prone atm (at least when you do it manually). Also the number of stations can vary with different ismn versions.
> Fix fixtures

- environment/qa4sm_env.yml
- validator/validation/batches.py
@pstradio found the bug that, if a bounding box was drawn over a subset of stations in a network, metadata and locations did not match anymore.
> Fix spatial subset

- UI/src/app/pages/my-datasets/my-datasets.component.html
- UI/src/app/pages/validate/validate.component.ts
- newest ISMN version set by default;
- information on the my-dataset page has been updated
> small frontend improvements done:

- UI/src/app/modules/validation-reference/components/validation-reference/validation-reference.component.html
- UI/src/app/pages/validate/validate.component.html
Tooltips added to spatial and temporal reference drop down lists;
Styling updated
> Add tooltip to reference

- validator/validation/validation.py
Window is currently +- selected value, should be +- 1/2 * selected value
> corrected temporal window

- UI/src/app/pages/validate/validate.component.ts
to handle a case when there is an updated on coordinates, but min values are bigger than max or the other way round
> setLimitationsOnGeographicalRange updated 

- UI/src/app/pages/home/home.component.html
- UI/src/app/pages/validate/validate.component.html
- email address added to the home page;
- information bar updated on the validate page;
> Small improvements

- api/views/upload_user_data_view.py
- docker/compose/prod/docker-compose.yml
- release-notes.md
- valentina/version.py
as it clears needed dependencies; 
new release prepared
> cleaning redundant metadata disabled

- UI/src/app/modules/dataset/components/dataset/dataset.component.ts
- UI/src/app/pages/validate/validate.component.ts
* update done to avoid hard-coded names
* sorting function updated
> Fix setting version list (#895)

- environment/qa4sm_env.yml
- validator/tests/auxiliary_functions.py
- validator/tests/test_validation.py
- validator/validation/batches.py
- validator/validation/readers.py
tests will probably fail. I will fix them. For the automatic dataset extension this should be everything that we have to change in the webservice. This is just to show that you don't have to wait for my changes to test deploy the other updates
> Add wrapper to extend time series with new data from airflow

- docker/base/install.sh
- docker/webapp/apache.conf
> added LimitRequestBody to apache.conf
