validator/tests/test_validation.py
since there are more graphs the assert statement is updated, and the double deletion of the test run is removed
=> fix the new test for ERA data set graphics

validator/templates/validator/ismn_dialog.html
- after clicking on select previously set values show up (or default if we click for the first time)
- dialog window doesn't close by itself if the alert shows up (when depth_to <depth_from) but first appropriate values have to be set
=> Depth filter corrections

validator/templates/validator/validate.html
function for switching months triggered not only by 'span' but also by 'a' tag around that 'span'.
=> calendar bug fixed

validator/forms/validation_run.py, validator/templates/validator/validate.html, validator/tests/test_views.py, validator/urls.py, validator/validation/globals.py, validator/validation/validation.py, validator/views/validation.py
* Revert "updating my fork"
* Updating my fork (#18)
* Update variables.json (#84)
Geophysical range for ESA CCI active changed to 0-100 instead of 0-1.
* Test master (#108)
* Add option to deactivate scaling (#98)
Co-authored-by: Wolfgang Preimesberger <wolfgang.preimesberger@geo.tuwien.ac.at>
* Bug fixing (#99)
* Update versions.json
* Update scheme.css
some styling added so that filter descriptions for smos don't cause a shift in the question mark sign
* Update filter_checkbox_option.html
Comment removed
* Ismn dialog window (#100)
* Qa4sm 389 ismn dialog window (#80)
* Revert "updating my fork"
* a bug fixed - default depth values were passed to the database instead of the ones chosen by user
* changed id of a checkbox for parametrized filters and the regular id passed into a hidden …
=> Qa4sm 241 update time ranges (#109)

environment/create_conda_env.sh, environment/qa4sm_env.yml, validator/templates/validator/datasets.html, validator/tests/test_validation.py, validator/validation/globals.py
* using ascat, smos and smap as reference require qa4sm-reader 0.3.4 or higher
* ascat, smap and smos removed from NOT_AS_REFERENCE list, but the list left just in case
* comment refering to datasets excluded from being used as reference ones improved, so that it shows only when there are such datasets
* link to the appropriate repository instead of verion number insterted for qa4sm-reader package
* test for smap validation used as a reference one added
* env .yml file improved
=> Qa4sm 408 smos smap ascat (#148)

validator/static/css/scheme.css
so that instead of: ![Screenshot from 2021-03-15 09-36-24](https://user-images.githubusercontent.com/57092960/111127745-76288680-8574-11eb-8b99-6ac10746fdd7.png)
we have:
=> small styling changes added

validator/forms/custom_widgets.py, validator/forms/data_configuration.py, validator/forms/validation_run.py, validator/static/css/scheme.css, validator/templates/validator/published_results.html, validator/templates/validator/result.html, validator/templates/validator/user_runs.html, validator/templates/validator/validate.html, validator/templates/widgets/filter_checkbox_option.html, validator/tests/test_views.py, validator/views/validation.py
* read filters and datasets from validation run
* added button to rerun validation
* selecting correct filters
* also remember version and variable; tests
* better visuals
- better button name
- better button order
- dates without time
- button on result page
* test for empty initial_filters
* test if initial filters is empty
* infer initial values also from POST
* fixes
* only change interval if it was not already set
* fixed validation time
* started work on parametrised filters
* redirecting with some parameters when there exists a validation
* test for existing validation updated according to changes in passing information
* running setTcLock so that it is possible to switch on and switch off tcol if more than 2 datasets are rendered by default
* pass parametrised filters and params …
=> Load settings (#159)

environment/qa4sm_env.yml
New qa4sm_reader version is v0.4.4 - Confidence Intervals are included in the boxplots
=> changed reader version in env

UI/src/app/modules/validation-result/components/summary-statistics/summary-statistics.component.html, api/views/serving_file_view.py, api/views/validation_run_view.py, environment/qa4sm_env.yml, validator/validation/graphics.py
Adapts QA4SM to read the .csv file generated by the QA4SM reader release v0.6.3.
- If the .csv file is present in the results, this is opened (validations with reader > v0.6.3)
- If not, and file size < 100 MB, the table is created on the fly
- Else, error message is shown
**Important**: this PR is only compatible with qa4sm reader >= 0.6.3.
=> Automatic statistics table to .csv 

environment/qa4sm_env.yml
Updates Pytesmo after this PR: https://github.com/TUW-GEO/pytesmo/pull/256
Which solves the `('snr', dataset)` error : https://github.com/TUW-GEO/pytesmo/issues/251
=> Updated pytesmo version in env

validator/fixtures/filters.json, validator/tests/test_filtering.py, validator/validation/filters.py
Fix for SMOS L3 RFI filtering. After a communication from the CESBIO team, the `Rfi_Prob` field (15-daily RFI probability) is dropped in the RFI filtering since 0 values are erroneously written as NaN, leading to correct SM values being filtered out.
=> Fixed SMOS RFI filtering

environment/qa4sm_env.yml, validator/tests/test_validation.py
I adapted the long-running tests (as mentioned in #535) based on the ok_points they had when using the old pytesmo version. I also changed the NaN-ratio test from a fixed ratio to a ratio depending on the number of error points. The test now basically makes sure that all errors which could lead to no metric being calculated are captured. Asserting that the error points is as expected should be done before calling check_results, as it is currently done in most tests.
@sheenaze test_validation_smap_ref had only 6 ok_points of 140 total_points, do you know if this is expected?
=> adapted tests

validator/tests/test_filtering.py, validator/validation/filters.py, validator/validation/readers.py
This PR comes as a workaround for the fact that 0.0 values in the SMOS L2 data set were reprocessed as NaNs (due to the fillvalue = 0.0). It can be rolled back after a reprocessing of SMOS L2 (after PM6)
=> Smos L2 filtering NaNs

validator/validation/validation.py
Now that the error codes are returned, it can be useful to see the results even if the calculation failed for all points. To fully work, some changes in qa4sm-reader are still required (https://github.com/awst-austria/qa4sm-reader/pull/60).
=> save validation also if all points failed

validator/tests/test_filtering.py, validator/validation/readers.py
After removing NaNs from SMOS L2 data set (reprocessed), ad hoc reader adapter for SMOS L2 can be removed.
=> removed SMOS L2 reader adapter

validator/fixtures/variables.json
The valid range of in situ is currently 0.0 - 1.0. However, 0.0 volumetric sm is hardly occurring in practice, and more often indicates a sensor malfunctioning.
While this should be dealt with in the ISMN data based through flagging, for many sensors it is still an issue. 
The 0.001 - 1.0 range should limit the impact of sensor malfunctioning.
=> removed 0.0 as valid lower thres. for ISMN

environment/qa4sm_env.yml, validator/models/dataset.py, validator/tests/test_models.py, validator/validation/validation.py
I added the max_dist keyword for the datasets that will then be used by the pytesmo data manager.
Currently I get the resolution from the `Dataset` model, @sheenaze, so you can in the GUI just adapt `dataset.resolution` for the user data.
=> maxdist for datasets

validator/fixtures/filters.json, validator/mailer.py, validator/validation/readers.py
Fixing differences in exact time stamp of the SBPCA data leading to failing temp. matching in some locations when choosing a 1H window (time differences were up to 40 minutes).
=> Use time stamp adapter to compute exact time

validator/fixtures/versions.json, validator/tests/auxiliary_functions.py, validator/tests/test_filtering.py, validator/validation/readers.py
Testdata updated for new SMOS L2 Format
Data transferred to server (but not replaced old data yet)
We have to coordinate when we deploy this, so we can change the path on the server
=> Change reader for new SMOS L2 Format and add overpass filter

docker/base/install.sh, docker/webapp/apache.conf
Changes
- Allow >1 GB uploads: Set LimitRequestBody in Apache config.
- Auto‑accept Conda licenses: Update docker/base/install.sh to include the Conda flag for channel Terms of Service.
=> Fix ‘413 Request Entity Too Large’ error for uploads over 1 GB
